[input]
filename = "fishes.svg"

[output]
type = "png"
filename = "%b-%n.%e"

[[output.slides]]
name = "blue background"
include = ["L0"]

[[output.slides]]
name = "day sky"
include = ["L0", "L1"]

[[output.slides]]
name = "sun"
include = ["#0-#2"]

[[output.slides]]
name = "red fish"
include = ["#0-#3"]

[[output.slides]]
name = "both fishes"
include = ["#0-#4"]

[[output.slides]]
name = "day chat"
include = ["#0-#5"]

[[output.slides]]
name = "night sky"
include = ["#0-#6"]
exclude = ["L5 msg:greetings"]

[[output.slides]]
name = "moon"
based-on = "night sky"
include = ["#7"]

[[output.slides]]
name = "1star"
based-on = "moon"
include = ["#8"]

[[output.slides]]
name = "2stars"
based-on = "1star"
include = ["#9"]

[[output.slides]]
name = "3stars"
based-on = "2stars"
include = ["#10"]

[[output.slides]]
name = "4stars"
based-on = "3stars"
include = ["#11"]

[[output.slides]]
name = "night chat"
based-on = "4stars"
include = ["#12"]

[[output.slides]]
name = "end"
based-on = "4stars"

